version: 2
jobs:
  build_app:
    docker:
      - image: circleci/node:8.11-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo npm install -g bower mocha gulp
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "bower.json" }}
      - run:
          name: Install npm modules
          command: npm install
      - run:
          name: Install bower componets
          command: bower install --allow-root -s -F
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "bower.json" }}
          paths:
            - node_modules
            - bower_components
      - run:
          name: Build
          command: gulp
      - persist_to_workspace:
          root: .
          paths: dist
  test_app:
    environment:
      PORT: 3001
      SERVERHOST: test-form.io
      SERVERPROTOCOL: https
    docker:
      - image: circleci/node:8.11-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "bower.json" }}
      - attach_workspace:
          at: .
      - run:
          name: Start Server
          background: true
          command: npm start
      - run:
          name: Install Sauce Labs and Set Up Tunnel
          background: true
          command: |
            curl https://saucelabs.com/downloads/sc-4.5.0-linux.tar.gz -o saucelabs.tar.gz
            tar -xzf saucelabs.tar.gz
            cd sc-*
            bin/sc -u ${SAUCELABS_USER} -k ${SAUCELABS_KEY} --readyfile ~/sauce_is_ready
            wget --retry-connrefused --no-check-certificate -T 60 localhost:4445  # wait for app to be ready
      - run: sudo bash -c "echo \"127.0.0.1 portal.localhost\" >> /etc/hosts"
      - run: mkdir ./test/screenshots
      - run:
          name: Wait for saucelabs
          command: while [ ! -e ~/sauce_is_ready ]; do sleep 1; done
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: ./test/screenshots
      - run: # wait for Sauce Connect to close the tunnel
          command: pkill sc
  deploy:
    environment:
      AWS_DEFAULT_REGION: "us-west-2"
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - attach_workspace:
          at:
            dist
      - run:
          name: Build tgz
          command: cd dist/dist && tar -czvf ../../${CIRCLE_TAG}.tgz *
      - run:
          name: Upload to s3
          command: aws s3 cp ${CIRCLE_TAG}.tgz s3://formio-app-releases/${CIRCLE_TAG}.tgz

workflows:
  version: 2
  do-build:
    jobs:
      - build_app:
          filters:
            tags:
              only: /.*/
      - test_app:
          requires:
            - build_app
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test_app
          filters:
            tags:
              only: /^\d+\.\d+\.\d+.*/
            branches:
              ignore: /.*/
